#ifndef QUEUE_H
#define QUEUE_H

#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>

/**
 * API to write data to the queue generated by producer.
 */
uint8_t write_queue(uint8_t input[], uint8_t numBytes);

/**
 * API allows reading from the queue by the consumer.
 * returns the number of bytes successfully read.
 * read data is copied to output array whose is reference is received
 * as input arg.
 */
uint8_t read_queue(uint8_t output[], uint8_t outputSize);

void printBytes(uint8_t data[], uint8_t len, char str[]);

#endif
